export const QUOTES = [
    {
        quote: "The impediment to action advances action. What stands in the way becomes the way.",
        firstName: "Marcus",
        lastName: "Aurelius",
        image: "Marcus",
        fact: "Marcus Aurelius was a Roman emperor and philosopher, known for his book 'Meditations.'",
        id: 1,
        favorite: false,
    },
    {
        quote: "The best revenge is not to be like your enemy.",
        firstName: "Marcus",
        lastName: "Aurelius",
        image: "Marcus",
        fact: "Marcus Aurelius was a Roman emperor and philosopher, known for his book 'Meditations.'",
        id: 0,
        favorite: false,
    },
    {
        quote: "Happiness and freedom begin with a clear understanding of one principle: Some things are within our control, and some things are not.",
        firstName: "Epictetus",
        lastName: "",
        image: "Epictetus",
        fact: "Epictetus was a Greek philosopher and former slave, whose teachings focused on personal freedom and the importance of self-discipline.",
        id: 2,
        favorite: false,
    },
    {
        quote: "Waste no more time arguing what a good man should be. Be one.",
        firstName: "Marcus",
        lastName: "Aurelius",
        image: "Marcus",
        fact: "Marcus Aurelius served as the Roman emperor from 161 to 180 AD.",
        id: 3,
        favorite: false,
    },
    {
        quote: "Man conquers the world by conquering himself.",
        firstName: "Chrysippus",
        lastName: "of Soli",
        image: "Chrysippus",
        fact: "Chrysippus was a Greek philosopher and the third head of the Stoic school of philosophy.",
        id: 4,
        favorite: false,
    },
    {
        quote: "The happiness of your life depends upon the quality of your thoughts.",
        firstName: "Seneca",
        lastName: "the Younger",
        image: "Seneca",
        fact: "Seneca the Younger was a Roman Stoic philosopher, statesman, and dramatist.",
        id: 5,
        favorite: false,
    },
    {
        quote: "You have power over your mind — not outside events. Realize this, and you will find strength.",
        firstName: "Marcus",
        lastName: "Aurelius",
        image: "Marcus",
        fact: "Marcus Aurelius was the last of the Five Good Emperors of Rome.",
        id: 6,
        favorite: false,
    },
    {
        quote: "Difficulties strengthen the mind, as labor does the body.",
        firstName: "Seneca",
        lastName: "the Younger",
        image: "Seneca",
        fact: "Seneca the Younger was a tutor and advisor to the Roman emperor Nero.",
        id: 7,
        favorite: false,
    },
    {
        quote: "Wealth consists not in having great possessions, but in having few wants.",
        firstName: "Epictetus",
        lastName: "",
        image: "Epictetus",
        fact: "Epictetus taught that philosophy is a way of life and emphasized the importance of inner freedom.",
        id: 8,
        favorite: false,
    },
    {
        quote: "The world turns aside to let any man pass who knows where he is going.",
        firstName: "Seneca",
        lastName: "the Younger",
        image: "Seneca",
        fact: "Seneca the Younger was a prominent Stoic philosopher during the Roman Empire.",
        id: 9,
        favorite: false,
    },
    {
        quote: "You have within you right now, everything you need to deal with whatever the world can throw at you.",
        firstName: "Marcus",
        lastName: "Aurelius",
        image: "Marcus",
        fact: "Marcus Aurelius is often considered one of the most important Stoic philosophers.",
        id: 10,
        favorite: false,
    },
    {
        quote: "It's not what happens to you, but how you react to it that matters.",
        firstName: "Epictetus",
        lastName: "",
        image: "Epictetus",
        fact: "Epictetus taught that philosophy is a way of life and should be practiced daily.",
        id: 11,
        favorite: false,
    },
    {
        quote: "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment.",
        firstName: "Marcus",
        lastName: "Aurelius",
        image: "Marcus",
        fact: "Marcus Aurelius was a practitioner of Stoicism and believed in the power of one's perception.",
        id: 12,
        favorite: false,
    },
    {
        quote: "Don't explain your philosophy. Embody it.",
        firstName: "Epictetus",
        lastName: "",
        image: "Epictetus",
        fact: "Epictetus emphasized the importance of living in accordance with one's philosophy.",
        id: 13,
        favorite: false,
    },
    {
        quote: "The more we value things outside our control, the less control we have.",
        firstName: "Epictetus",
        lastName: "",
        image: "Epictetus",
        fact: "Epictetus believed that true freedom comes from focusing on what is within our control.",
        id: 14,
        favorite: false,
    },
    {
        quote: "The soul becomes dyed with the color of its thoughts.",
        firstName: "Marcus",
        lastName: "Aurelius",
        image: "Marcus",
        fact: "Marcus Aurelius was a philosopher-king, known for his Stoic reflections on life and virtue.",
        id: 15,
        favorite: false,
    },
    {
        quote: "Choose not to be harmed, and you won't feel harmed. Don't feel harmed, and you haven't been.",
        firstName: "Marcus",
        lastName: "Aurelius",
        image: "Marcus",
        fact: "Marcus Aurelius wrote his philosophical thoughts as personal reflections rather than for publication.",
        id: 16,
        favorite: false,
    },
    {
        quote: "If it's endurable, then endure it. Stop complaining.",
        firstName: "Seneca",
        lastName: "the Younger",
        image: "Seneca",
        fact: "Seneca the Younger was a prominent Stoic philosopher, statesman, and tragedian.",
        id: 17,
        favorite: false,
    },
    {
        quote: "It is not the man who has too little that is poor, but the one who hankers after more.",
        firstName: "Seneca",
        lastName: "the Younger",
        image: "Seneca",
        fact: "Seneca the Younger was a tutor and advisor to the Roman emperor Nero.",
        id: 18,
        favorite: false,
    },
    {
        quote: "First say to yourself what you would be; and then do what you have to do.",
        firstName: "Epictetus",
        lastName: "",
        image: "Epictetus",
        fact: "Epictetus taught that the key to happiness is aligning our desires with our actions.",
        id: 19,
        favorite: false,
    },
    {
        quote: "What really frightens and dismays us is not external events themselves, but the way in which we think about them.",
        firstName: "Epictetus",
        lastName: "",
        image: "Epictetus",
        fact: "Epictetus believed that our perception of events shapes our emotional responses.",
        id: 20,
        favorite: false,
    },
    {
        quote: "The best revenge is not to be like your enemy.",
        firstName: "Marcus",
        lastName: "Cicero",
        image: "Cicero",
        fact: "Cicero was a Roman philosopher, politician, and orator who greatly influenced Western thought.",
        id: 21,
        favorite: false,
    },
    {
        quote: "If a man knows not to which port he sails, no wind is favorable.",
        firstName: "Seneca",
        lastName: "the Younger",
        image: "Seneca",
        fact: "Seneca the Younger was a prominent Stoic philosopher and advisor to Emperor Nero.",
        id: 22,
        favorite: false,
    },
    {
        quote: "It is not the man who has too little, but the man who craves more, that is poor.",
        firstName: "Seneca",
        lastName: "the Younger",
        image: "Seneca",
        fact: "Seneca the Younger was a Roman Stoic philosopher and playwright.",
        id: 23,
        favorite: false,
    },
    {
        quote: "No person has the power to have everything they want, but it is in their power not to want what they don't have, and to cheerfully put to good use what they do have.",
        firstName: "Seneca",
        lastName: "the Younger",
        image: "Seneca",
        fact: "Seneca the Younger was a prominent Stoic philosopher during the Roman Empire.",
        id: 24,
        favorite: false,
    },
    {
        quote: "What is the point of dragging up sufferings that are over, of being miserable now because you were then?",
        firstName: "Seneca",
        lastName: "the Younger",
        image: "Seneca",
        fact: "Seneca the Younger was a Roman Stoic philosopher, statesman, and tragedian.",
        id: 25,
        favorite: false,
    },
    {
        quote: "If you wish to be loved, love.",
        firstName: "Seneca",
        lastName: "the Younger",
        image: "Seneca",
        fact: "Seneca the Younger was a tutor and advisor to the Roman emperor Nero.",
        id: 26,
        favorite: false,
    },
    {
        quote: "The whole future lies in uncertainty: live immediately.",
        firstName: "Seneca",
        lastName: "the Younger",
        image: "Seneca",
        fact: "Seneca the Younger was a prominent Stoic philosopher during the Roman Empire.",
        id: 27,
        favorite: false,
    },
    {
        quote: "It is not the man who has too little that is poor, but the one who hankers after more.",
        firstName: "Marcus",
        lastName: "Cicero",
        image: "Cicero",
        fact: "Cicero was a Roman philosopher, politician, and orator who greatly influenced Western thought.",
        id: 28,
        favorite: false,
    },
    {
        quote: "A room without books is like a body without a soul.",
        firstName: "Marcus",
        lastName: "Cicero",
        image: "Cicero",
        fact: "Cicero was a Roman philosopher, politician, and orator who greatly influenced Western thought.",
        id: 29,
        favorite: false,
    },
    {
        quote: "The wise man sees in the misfortune of others what he should avoid.",
        firstName: "Marcus",
        lastName: "Cicero",
        image: "Cicero",
        fact: "Cicero was a Roman philosopher, politician, and orator who greatly influenced Western thought.",
        id: 30,
        favorite: false,
    },
    {
        quote: "The mind is everything. What you think you become.",
        firstName: "Marcus",
        lastName: "Cicero",
        image: "Cicero",
        fact: "Cicero was a Roman philosopher, politician, and orator who greatly influenced Western thought.",
        id: 31,
        favorite: false,
    },
    {
        quote: "Gratitude is not only the greatest of virtues but the parent of all others.",
        firstName: "Marcus",
        lastName: "Cicero",
        image: "Cicero",
        fact: "Cicero was a Roman philosopher, politician, and orator who greatly influenced Western thought.",
        id: 32,
        favorite: false,
    },
    {
        quote: "The first step in the acquisition of wisdom is silence, the second listening, the third memory, the fourth practice, the fifth teaching others.",
        firstName: "Marcus",
        lastName: "Cicero",
        image: "Cicero",
        fact: "Cicero was a Roman philosopher, politician, and orator who greatly influenced Western thought.",
        id: 33,
        favorite: false,
    },
    {
        quote: "True law is right reason in agreement with nature; it is of universal application, unchanging and everlasting.",
        firstName: "Marcus",
        lastName: "Cicero",
        image: "Cicero",
        fact: "Cicero was a Roman philosopher, politician, and orator who greatly influenced Western thought.",
        id: 34,
        favorite: false,
    },
    {
        quote: "It is not the man who has too little, but the man who craves more, that is poor.",
        firstName: "Chrysippus",
        lastName: "of Soli",
        image: "Chrysippus",
        fact: "Chrysippus was a Greek philosopher and the third head of the Stoic school of philosophy.",
        id: 35,
        favorite: false,
    },
    {
        quote: "If you wish to be a writer, write.",
        firstName: "Epictetus",
        lastName: "",
        image: "Epictetus",
        fact: "Epictetus was a Greek philosopher and former slave, known for his teachings on personal freedom and self-discipline.",
        id: 36,
        favorite: false,
    },
    {
        quote: "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control.",
        firstName: "Epictetus",
        lastName: "",
        image: "Epictetus",
        fact: "Epictetus emphasized the importance of inner freedom and the pursuit of a virtuous life.",
        id: 37,
        favorite: false,
    },
];
