export const QUOTES = [
    {
        quote: "The best revenge is not to be like your enemy.",
        firstName: "Marcus",
        lastName: "Aurelius",
        // image: require("./path/to/image_1.png"),
        fact: "Marcus Aurelius was a Roman emperor and philosopher, known for his book 'Meditations.'",
        id: 1,
    },
    {
        quote: "Happiness and freedom begin with a clear understanding of one principle: Some things are within our control, and some things are not.",
        firstName: "Epictetus",
        lastName: "",
        // image: require("./path/to/image_2.png"),
        fact: "Epictetus was a Greek philosopher and former slave, whose teachings focused on personal freedom and the importance of self-discipline.",
        id: 2,
    },
    {
        quote: "Waste no more time arguing what a good man should be. Be one.",
        firstName: "Marcus",
        lastName: "Aurelius",
        // image: require("./path/to/image_1.png"),
        fact: "Marcus Aurelius served as the Roman emperor from 161 to 180 AD.",
        id: 3,
    },
    {
        quote: "Man conquers the world by conquering himself.",
        firstName: "Zeno",
        lastName: "of Citium",
        // image: require("./path/to/image_3.png"),
        fact: "Zeno of Citium was a Greek philosopher and the founder of the Stoic school of philosophy.",
        id: 4,
    },
    {
        quote: "The happiness of your life depends upon the quality of your thoughts.",
        firstName: "Seneca",
        lastName: "the Younger",
        // image: require("./path/to/image_4.png"),
        fact: "Seneca the Younger was a Roman Stoic philosopher, statesman, and dramatist.",
        id: 5,
    },
    {
        quote: "You have power over your mind — not outside events. Realize this, and you will find strength.",
        firstName: "Marcus",
        lastName: "Aurelius",
        // image: require("./path/to/image_1.png"),
        fact: "Marcus Aurelius was the last of the Five Good Emperors of Rome.",
        id: 6,
    },
    {
        quote: "Difficulties strengthen the mind, as labor does the body.",
        firstName: "Seneca",
        lastName: "the Younger",
        // image: require("./path/to/image_4.png"),
        fact: "Seneca the Younger was a tutor and advisor to the Roman emperor Nero.",
        id: 7,
    },
    {
        quote: "Wealth consists not in having great possessions, but in having few wants.",
        firstName: "Epictetus",
        lastName: "",
        // image: require("./path/to/image_2.png"),
        fact: "Epictetus taught that philosophy is a way of life and emphasized the importance of inner freedom.",
        id: 8,
    },
    {
        quote: "The world turns aside to let any man pass who knows where he is going.",
        firstName: "Seneca",
        lastName: "the Younger",
        // image: require("./path/to/image_4.png"),
        fact: "Seneca the Younger was a prominent Stoic philosopher during the Roman Empire.",
        id: 9,
    },
    {
        quote: "You have within you right now, everything you need to deal with whatever the world can throw at you.",
        firstName: "Marcus",
        lastName: "Aurelius",
        // image: require("./path/to/image_1.png"),
        fact: "Marcus Aurelius is often considered one of the most important Stoic philosophers.",
        id: 10,
    },
    {
        quote: "It's not what happens to you, but how you react to it that matters.",
        firstName: "Epictetus",
        lastName: "",
        // image: require("./path/to/image_2.png"),
        fact: "Epictetus taught that philosophy is a way of life and should be practiced daily.",
        id: 11,
    },
    {
        quote: "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment.",
        firstName: "Marcus",
        lastName: "Aurelius",
        // image: require("./path/to/image_1.png"),
        fact: "Marcus Aurelius was a practitioner of Stoicism and believed in the power of one's perception.",
        id: 12,
    },
    {
        quote: "Don't explain your philosophy. Embody it.",
        firstName: "Epictetus",
        lastName: "",
        // image: require("./path/to/image_2.png"),
        fact: "Epictetus emphasized the importance of living in accordance with one's philosophy.",
        id: 13,
    },
    {
        quote: "The more we value things outside our control, the less control we have.",
        firstName: "Epictetus",
        lastName: "",
        // image: require("./path/to/image_2.png"),
        fact: "Epictetus believed that true freedom comes from focusing on what is within our control.",
        id: 14,
    },
    {
        quote: "The soul becomes dyed with the color of its thoughts.",
        firstName: "Marcus",
        lastName: "Aurelius",
        // image: require("./path/to/image_1.png"),
        fact: "Marcus Aurelius was a philosopher-king, known for his Stoic reflections on life and virtue.",
        id: 15,
    },
    {
        quote: "Choose not to be harmed, and you won't feel harmed. Don't feel harmed, and you haven't been.",
        firstName: "Marcus",
        lastName: "Aurelius",
        // image: require("./path/to/image_1.png"),
        fact: "Marcus Aurelius wrote his philosophical thoughts as personal reflections rather than for publication.",
        id: 16,
    },
    {
        quote: "If it's endurable, then endure it. Stop complaining.",
        firstName: "Seneca",
        lastName: "the Younger",
        // image: require("./path/to/image_4.png"),
        fact: "Seneca the Younger was a prominent Stoic philosopher, statesman, and tragedian.",
        id: 17,
    },
    {
        quote: "It is not the man who has too little that is poor, but the one who hankers after more.",
        firstName: "Seneca",
        lastName: "the Younger",
        // image: require("./path/to/image_4.png"),
        fact: "Seneca the Younger was a tutor and advisor to the Roman emperor Nero.",
        id: 18,
    },
    {
        quote: "First say to yourself what you would be; and then do what you have to do.",
        firstName: "Epictetus",
        lastName: "",
        // image: require("./path/to/image_2.png"),
        fact: "Epictetus taught that the key to happiness is aligning our desires with our actions.",
        id: 19,
    },
    {
        quote: "What really frightens and dismays us is not external events themselves, but the way in which we think about them.",
        firstName: "Epictetus",
        lastName: "",
        // image: require("./path/to/image_2.png"),
        fact: "Epictetus believed that our perception of events shapes our emotional responses.",
        id: 20,
    },
];
